# Generated by Django 2.1.7 on 2019-11-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_remove_profile_albums_on_lineup'),
        ('music', '0005_auto_20191004_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_id', models.CharField(max_length=30)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='music.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_members', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
