language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE postgres;" -U postgres
  - python manage.py migrate --noinput

# command to run tests
script:
  - python manage.py test ratebum/apps/