# Generated by Django 2.1.7 on 2020-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_auto_20190831_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='radaritem',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
