# Generated by Django 2.1.7 on 2019-08-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='albums_on_radar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='artists_on_radar',
        ),
    ]
