# Generated by Django 2.1.7 on 2019-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190831_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=200),
        ),
    ]
