# Generated by Django 2.1.5 on 2019-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191003_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
