# Generated by Django 2.1.7 on 2020-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191004_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
